/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author Idawi
 */
public class AdminUtrustning extends javax.swing.JFrame {
private static InfDB idb;


    /**
     * Creates new form AdminUtrustning
     */
    public AdminUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
    }
    

        
        
        
        
        
        
        
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valjUKategoriMeny = new javax.swing.JLabel();
        uKategoriOkknapp = new javax.swing.JButton();
        valjUKategori = new javax.swing.JComboBox<>();
        valjNamnPaUtrustning = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        taBortUtrustning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        valjUKategoriMeny.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valjUKategoriMeny.setText("Välj kategori av utrustning");

        uKategoriOkknapp.setText("Välj");
        uKategoriOkknapp.setActionCommand("OK");

        valjUKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vapen", "Teknik", "Kommunikation" }));

        jLabel1.setText("Välj utrustning");

        taBortUtrustning.setText("Ta bort");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valjUKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valjUKategoriMeny))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(valjNamnPaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(taBortUtrustning)
                                .addGap(10, 10, 10)))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uKategoriOkknapp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjUKategoriMeny)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjUKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valjNamnPaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uKategoriOkknapp)
                    .addComponent(taBortUtrustning))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void valjUKategoriActionPerformed(java.awt.event.ActionEvent evt) {                                          
      
        
        visaUKategorilista.setText(" ");
        ArrayList<String> vapenLista;
        
        if(valjUKategori.getSelectedItem().equals("Vapen")) {
          
          try{
           String valdUKategori= valjUKategori.getSelectedItem().toString();
           String fraga = "SELECT benamning from Utrustning, Vapen where Utrustning.Utrustnings_ID = Vapen.Utrustnings_ID" ;
           vapenLista = idb.fetchColumn(fraga);
           
           for(String namnAvUKategori: vapenLista){
            visaUKategorilista.append(namnAvUKategori + "\t");
           }
           
          }catch(InfException e){
              JOptionPane.showMessageDialog(null, "Något gick fel");
          }
        }
        
        
         ArrayList<String> teknikLista;
        
        if(valjUKategori.getSelectedItem().equals("Teknik")) {
          
          try{
           String valdUKategori = valjUKategori.getSelectedItem().toString();
           String fraga = "SELECT benamning from Utrustning, Teknik where Utrustning.Utrustnings_ID = Teknik.Utrustnings_ID" ;
           teknikLista = idb.fetchColumn(fraga);
           
           for(String namnAvUKategori: teknikLista){
            visaUKategorilista.append(namnAvUKategori + "\t");
           }
           
          }catch(InfException e){
              JOptionPane.showMessageDialog(null, "Något gick fel");
          }
        }
        
        
         ArrayList<String> kommunikationLista;
        
        if(valjUKategori.getSelectedItem().equals("Kommunikation")) {
          
          try{
           String valdUKategori = valjUKategori.getSelectedItem().toString();
           String fraga = "SELECT benamning from Utrustning, kommunikation where Utrustning.Utrustnings_ID = kommunikation.Utrustnings_ID" ;
           kommunikationLista = idb.fetchColumn(fraga);
           
           for(String namnAvUKategori: kommunikationLista){
            visaUKategorilista.append(namnAvUKategori + "\t");
           }
           
          }catch(InfException e){
              JOptionPane.showMessageDialog(null, "Något gick fel");
          }
        }
          
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUtrustning(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton taBortUtrustning;
    private javax.swing.JButton uKategoriOkknapp;
    private javax.swing.JComboBox<String> valjNamnPaUtrustning;
    private javax.swing.JComboBox<String> valjUKategori;
    private javax.swing.JLabel valjUKategoriMeny;
    // End of variables declaration//GEN-END:variables
}
