 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author filippabostrom
 */
public class AlienMeny extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form AlienMeny
     */
    public AlienMeny(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllBoxMedAlienNamn();
    }
    
    private void fyllBoxMedAlienNamn(){
        
         String fraga = "SELECT namn from Alien";
        
        ArrayList <String> allaAlienNamn;
        
        try {
            allaAlienNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAlienNamn) {
                valjInloggadAlien.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
        
       //en metod som ställer en sql fråga mot databasen som hämtar ut samtliga aliennamn från tabellen alien som sedan fyller komboxoen med samtliga namn vid instansiering.    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        andraLosenordAlien = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        visaOmradeschef = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visaAlienOmradeschef = new javax.swing.JTextArea();
        valjInloggadAlien = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        loggaUtKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Välkommen tillbaka alien!");

        andraLosenordAlien.setText("Ändra lösenord");
        andraLosenordAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraLosenordAlienActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Visa info ");

        visaOmradeschef.setText("Områdeschef");
        visaOmradeschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaOmradeschefActionPerformed(evt);
            }
        });

        visaAlienOmradeschef.setColumns(20);
        visaAlienOmradeschef.setRows(5);
        jScrollPane1.setViewportView(visaAlienOmradeschef);

        jLabel3.setText("Vem är inloggad?");

        loggaUtKnapp.setText("Logga ut");
        loggaUtKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggaUtKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valjInloggadAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(visaOmradeschef)))
                        .addGap(144, 144, 144))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loggaUtKnapp)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(andraLosenordAlien)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(andraLosenordAlien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjInloggadAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visaOmradeschef))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)))
                .addGap(2, 2, 2)
                .addComponent(loggaUtKnapp)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void andraLosenordAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraLosenordAlienActionPerformed
       new AndraLosenordAlien(idb).setVisible(true); //gör andraLosenordAlien menyn synlig 
    }//GEN-LAST:event_andraLosenordAlienActionPerformed

    private void visaOmradeschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaOmradeschefActionPerformed
        
        visaAlienOmradeschef.setText("");
        try{
        String valtNamn = valjInloggadAlien.getSelectedItem().toString();
        //valtNamn håller samtliga alien som går att välja på i komboboxen.
        //sql fråga ställs mot databasen som hämtar ut vilken agent som är områdeschef för ett område för den specifika alien 
        String fraga = "SELECT Agent.Namn from Agent join Omradeschef on Agent.Agent_ID = Omradeschef.Agent_ID join Alien on Alien.Plats = Omradeschef.Omrade where Alien.Namn = " + "'" + valtNamn + "'" ;
        String resultat = idb.fetchSingle(fraga);
        visaAlienOmradeschef.append(resultat);
        //metod för att visa alien som är områdeschef 
    
    //en catch som fångar inmatningsfel som gör att applikationen inte "kraschar"
    }catch(InfException e) {
    JOptionPane.showMessageDialog(null, "Något gick fel");
                    System.out.println("Internt felmeddelande" + e.getMessage());
}

    }//GEN-LAST:event_visaOmradeschefActionPerformed

    private void loggaUtKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggaUtKnappActionPerformed
        new InloggningsSida(idb).setVisible(true);
        
    }//GEN-LAST:event_loggaUtKnappActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton andraLosenordAlien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loggaUtKnapp;
    private javax.swing.JComboBox<String> valjInloggadAlien;
    private javax.swing.JTextArea visaAlienOmradeschef;
    private javax.swing.JButton visaOmradeschef;
    // End of variables declaration//GEN-END:variables
}
