/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author filippabostrom
 */
public class AndraInformationOmAlien extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form AndraInformationOmAlien
     */
    public AndraInformationOmAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllBoxMedNamn();
        skrivInInformationRubrik.setVisible(false);
        skrivInNytt.setVisible(false);
        ändraKnapp.setVisible(false);
        valjInfo.setVisible(false);
        rubrikVadVillAndra.setVisible(false);
        boxMedAgenter.setVisible(false);
        valjAgentKnapp.setVisible(false);
        
        
        
    }
    
    private void fyllBoxMedNamn() {
        String fraga = "SELECT namn from Alien";
        
        ArrayList <String> allaAlienNamn;
        
        try {
            allaAlienNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAlienNamn) {
                boxAlienNamn.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    private void fyllBoxMedAgentNamn() {
        
         
        String fraga = "SELECT namn from Agent";
        
        ArrayList <String> allaAgentNamn;
        
        try {
            allaAgentNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAgentNamn) {
                boxMedAgenter.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rubrikVadVillAndra = new javax.swing.JLabel();
        valjInfo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        boxAlienNamn = new javax.swing.JComboBox<>();
        valjAlien = new javax.swing.JButton();
        skrivInNytt = new javax.swing.JTextField();
        ändraKnapp = new javax.swing.JButton();
        skrivInInformationRubrik = new javax.swing.JLabel();
        boxMedAgenter = new javax.swing.JComboBox<>();
        valjAgentKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rubrikVadVillAndra.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rubrikVadVillAndra.setText("Vad vill du ändra?");

        valjInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alien_ID", "Losenord", "Plats", "Namn", "Ansvarig_Agent", "Telefon" }));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Välj alien");

        valjAlien.setText("Välj");
        valjAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjAlienActionPerformed(evt);
            }
        });

        skrivInNytt.setColumns(8);

        ändraKnapp.setText("Ändra");
        ändraKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ändraKnappActionPerformed(evt);
            }
        });

        skrivInInformationRubrik.setText("Skriv in ny infromation");

        valjAgentKnapp.setText("Välj Agent");
        valjAgentKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjAgentKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valjAgentKnapp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(boxAlienNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(valjAlien)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valjInfo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxMedAgenter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ändraKnapp)
                            .addComponent(skrivInNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rubrikVadVillAndra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(skrivInInformationRubrik)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxAlienNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valjAlien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rubrikVadVillAndra)
                    .addComponent(skrivInInformationRubrik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skrivInNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valjAgentKnapp)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ändraKnapp)
                    .addComponent(boxMedAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valjAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjAlienActionPerformed
        valjInfo.setVisible(true);
        rubrikVadVillAndra.setVisible(true);
        skrivInInformationRubrik.setVisible(true);
        skrivInNytt.setVisible(true);
        ändraKnapp.setVisible(true);
        valjAgentKnapp.setVisible(true);
        
    }//GEN-LAST:event_valjAlienActionPerformed

    private void ändraKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ändraKnappActionPerformed
        
        try{
        String alienNamn =  boxAlienNamn.getSelectedItem().toString();
        String egenskaper = valjInfo.getSelectedItem().toString();  
        String nyInfo = skrivInNytt.getText();
        
        if(egenskaper.equals("Alien_ID")){
        idb.update("UPDATE alien SET Alien_ID = "+ "'"+ nyInfo + "'" + " where namn = "+ "'" + alienNamn +"'");
        String fragaAlienID = "Select Alien_ID from Alien where namn =" + "'" +nyInfo + "'";
        String resultatAlien = idb.fetchSingle(fragaAlienID);
        int alienIDInt = Integer.parseInt(resultatAlien);
        idb.update("UPDATE alien SET Alien_ID = "+ alienIDInt + " where namn = "+ "'" + alienNamn +"'");
        rubrikVadVillAndra.setText("Ny ändring har gjorts");
        }
        
        
        
        if(egenskaper.equals("Namn")){
        idb.update("UPDATE alien SET Namn = "+ "'"+ nyInfo + "'" + " where namn = "+ "'" + alienNamn +"'");
        rubrikVadVillAndra.setText("Ny ändring har gjorts");
        }
        if(egenskaper.equals("Plats")){
        String fragaPlats = "Select Plats_ID from Plats where Benamning =" + "'" +nyInfo+"'";
        String resultatInt = idb.fetchSingle(fragaPlats);
        int platsInt = Integer.parseInt(resultatInt);
        idb.update("UPDATE alien SET Plats = "+ platsInt + " where namn = "+ "'" + alienNamn +"'");
        rubrikVadVillAndra.setText("Ny ändring har gjorts");
        }
        
        if(egenskaper.equals("Telefon")){
        idb.update("UPDATE alien SET Telefon = "+ "'"+ nyInfo + "'" + " where namn = "+ "'" + alienNamn +"'");
        rubrikVadVillAndra.setText("Ny ändring har gjorts");
        }
        
        if(egenskaper.equals("Ansvarig_Agent")){
         
        
         String hamtaNamn = boxMedAgenter.getSelectedItem().toString();
         String fragaAgent = "Select Agent_ID from Agent where Namn ="  + "'"+ hamtaNamn+"'";
         String resultatAgent = idb.fetchSingle(fragaAgent);
         int agentInt = Integer.parseInt(resultatAgent);
         idb.update("UPDATE alien SET Ansvarig_Agent = "+ agentInt + " where namn = "+ "'" + alienNamn +"'");
         
         
         rubrikVadVillAndra.setText("Ny ändring har gjorts");
        }
        
        
        
            
        }catch(InfException e) {
           JOptionPane.showMessageDialog(null, "något gick fel");
            System.out.println("internt felmeddelande" + e.getMessage());
        }
        
    }//GEN-LAST:event_ändraKnappActionPerformed

    private void valjAgentKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjAgentKnappActionPerformed
         boxMedAgenter.setVisible(true);
         skrivInInformationRubrik.setVisible(false);
         skrivInNytt.setVisible(false);
         fyllBoxMedAgentNamn();
         
    }//GEN-LAST:event_valjAgentKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraInformationOmAlien(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAlienNamn;
    private javax.swing.JComboBox<String> boxMedAgenter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel rubrikVadVillAndra;
    private javax.swing.JLabel skrivInInformationRubrik;
    private javax.swing.JTextField skrivInNytt;
    private javax.swing.JButton valjAgentKnapp;
    private javax.swing.JButton valjAlien;
    private javax.swing.JComboBox<String> valjInfo;
    private javax.swing.JButton ändraKnapp;
    // End of variables declaration//GEN-END:variables
}
