 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/**
 *
 * @author filippabostrom
 */
public class AndraLosenord extends javax.swing.JFrame {
 private static InfDB idb;
    /**
     * Creates new form AndraLosenord
     */
    public AndraLosenord(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllBoxMedAgentNamn();
    }

    private void fyllBoxMedAgentNamn() {
        
         
        String fraga = "SELECT namn from Agent";
        
        ArrayList <String> allaAgentNamn;
        
        try {
            allaAgentNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAgentNamn) {
                valjAnvandarnamnBox.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bytLosenRubrik = new javax.swing.JLabel();
        nuvarandeLosenRubrik = new javax.swing.JLabel();
        nyttLosenRubrik = new javax.swing.JLabel();
        nuvarandeLosen = new javax.swing.JPasswordField();
        nyttLosen = new javax.swing.JPasswordField();
        upprepaRubik = new javax.swing.JLabel();
        upprepaNyttLosen = new javax.swing.JPasswordField();
        knappByt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valjAnvandarnamnBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bytLosenRubrik.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bytLosenRubrik.setText("Byt lösenord");

        nuvarandeLosenRubrik.setText("Nuvarande lösenord:");

        nyttLosenRubrik.setText("Nytt lösenord:");

        nuvarandeLosen.setColumns(8);
        nuvarandeLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuvarandeLosenActionPerformed(evt);
            }
        });

        nyttLosen.setColumns(8);
        nyttLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyttLosenActionPerformed(evt);
            }
        });

        upprepaRubik.setText("Upprepa nytt lösenord:");

        upprepaNyttLosen.setColumns(8);
        upprepaNyttLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upprepaNyttLosenActionPerformed(evt);
            }
        });

        knappByt.setText("Byt lösenord");
        knappByt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knappBytActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj användarnamn:");

        valjAnvandarnamnBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjAnvandarnamnBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(knappByt)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bytLosenRubrik)
                        .addGap(232, 232, 232))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuvarandeLosenRubrik)
                            .addComponent(nuvarandeLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upprepaRubik)
                            .addComponent(upprepaNyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(valjAnvandarnamnBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nyttLosenRubrik))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bytLosenRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nyttLosenRubrik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjAnvandarnamnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuvarandeLosenRubrik)
                    .addComponent(upprepaRubik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuvarandeLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upprepaNyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(knappByt)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuvarandeLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuvarandeLosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuvarandeLosenActionPerformed

    private void knappBytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knappBytActionPerformed
        
        // metod som ändrar ett lösenord hos en Agent
        
        try{
        String losen = nuvarandeLosen.getText(); // hämtar det nuvarande lösenordet
        String losenNytt = nyttLosen.getText(); // hämtar det nya lösenordet
        String losenNyttNytt = upprepaNyttLosen.getText(); // hämtar det nya lösenordet igen
        String anvandarnamn = (String) valjAnvandarnamnBox.getSelectedItem(); // hämtar det användarnamn som är inloggad och som vill byta lösenord
        String fraga = "SELECT Losenord from Agent where Losenord =" + "'" + losen + "'"; // hämtar lösenordet från databasten som stämmer överens med det nuvarande lösenordet
        String resultat = idb.fetchSingle(fraga);
        if(losen.equals(resultat)&& losenNytt.equals(losenNyttNytt)){ // if-sats som kollar och med nuvarande lösenordet stämmer överns med databasen och att det nya lösenordet stämmer överns i båda textfälten
        losen = losenNytt; 
        idb.update("UPDATE agent SET losenord = " + "'" + losenNytt + "'" + " where namn = " + "'" + anvandarnamn + "'"); // här sker en updatering i databasen, där det nya lösenordet som valts sätts in som lösenord för den valda agenten

        bytLosenRubrik.setText("Ditt lösenord har ändrats");
        }
        else{
            JOptionPane.showMessageDialog(null, "Det gick inte att uppdatera lösenord");
        }
        
       
        }
        catch(InfException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_knappBytActionPerformed

    private void upprepaNyttLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upprepaNyttLosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upprepaNyttLosenActionPerformed

    private void nyttLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyttLosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyttLosenActionPerformed

    private void valjAnvandarnamnBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjAnvandarnamnBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valjAnvandarnamnBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraLosenord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraLosenord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraLosenord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraLosenord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraLosenord(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bytLosenRubrik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton knappByt;
    private javax.swing.JPasswordField nuvarandeLosen;
    private javax.swing.JLabel nuvarandeLosenRubrik;
    private javax.swing.JPasswordField nyttLosen;
    private javax.swing.JLabel nyttLosenRubrik;
    private javax.swing.JPasswordField upprepaNyttLosen;
    private javax.swing.JLabel upprepaRubik;
    private javax.swing.JComboBox<String> valjAnvandarnamnBox;
    // End of variables declaration//GEN-END:variables
}
