/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author filippabostrom
 */
public class AndraInformationOmAgenter extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form AndraInformationOmAgenter
     */
    public AndraInformationOmAgenter(InfDB idb) {
        initComponents();
        this.idb = idb;
        infoRubrik.setVisible(false);
        kategoriBox.setVisible(false);
        nyInfoTextRuta.setVisible(false);
        rubrik2.setVisible(false);
        boxMedOmraden.setVisible(false);
        boxMedStatus.setVisible(false);
        valjOmradeKnapp.setVisible(false);
        ValjStatusKnapp.setVisible(false);
        andraKnapp.setVisible(false);
                
                
        
    }
    
    
    private void fyllBoxMedAgentNamn() {
        
         
        String fraga = "SELECT namn from Agent";
        
        ArrayList <String> allaAgentNamn;
        
        try {
            allaAgentNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAgentNamn) {
                boxMedAgenter.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    private void fyllBoxMedOmrade () {
        
        String fraga = "Select Benamning from Omrade";
        
        ArrayList<String> allaOmraden;
        
        try{
            
            allaOmraden = idb.fetchColumn(fraga);
            
            for(String omrade : allaOmraden){
                boxMedOmraden.addItem(omrade);
            }
        }catch(InfException e){
            JOptionPane.showMessageDialog(null, "fel");
            
            
        }
        
        
        
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boxMedAgenter = new javax.swing.JComboBox<>();
        valjAgent = new javax.swing.JButton();
        infoRubrik = new javax.swing.JLabel();
        kategoriBox = new javax.swing.JComboBox<>();
        nyInfoTextRuta = new javax.swing.JTextField();
        rubrik2 = new javax.swing.JLabel();
        boxMedOmraden = new javax.swing.JComboBox<>();
        valjOmradeKnapp = new javax.swing.JButton();
        andraKnapp = new javax.swing.JButton();
        ValjStatusKnapp = new javax.swing.JButton();
        boxMedStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Välj agent");

        valjAgent.setText("Välj");
        valjAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjAgentActionPerformed(evt);
            }
        });

        infoRubrik.setText("Vad vill du ändra?");

        kategoriBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agent_ID", "Namn", "Telefon", "Administrator", "Losenord", "Omrade" }));

        nyInfoTextRuta.setColumns(8);

        rubrik2.setText("Skriv in ny information");

        valjOmradeKnapp.setText("Välj område");
        valjOmradeKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjOmradeKnappActionPerformed(evt);
            }
        });

        andraKnapp.setText("Ändra");
        andraKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraKnappActionPerformed(evt);
            }
        });

        ValjStatusKnapp.setText("Välj status");
        ValjStatusKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValjStatusKnappActionPerformed(evt);
            }
        });

        boxMedStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "J" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kategoriBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boxMedOmraden, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valjOmradeKnapp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ValjStatusKnapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxMedStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(boxMedAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valjAgent)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoRubrik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rubrik2)
                            .addComponent(nyInfoTextRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(andraKnapp)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxMedAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valjAgent))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoRubrik)
                    .addComponent(rubrik2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyInfoTextRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjOmradeKnapp)
                    .addComponent(ValjStatusKnapp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxMedOmraden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxMedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(andraKnapp)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void andraKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraKnappActionPerformed
       
        try{
           
         String agentNamn = boxMedAgenter.getSelectedItem().toString();
         String kategori = kategoriBox.getSelectedItem().toString();
         String nyInfo = nyInfoTextRuta.getText();
         
         if(kategori.equals("Agent_ID")) {
         String nyttID = nyInfo;
         int agentID = 
        
             
        idb.update("UPDATE Agent SET Agent_ID = "+ nyInfo + " where namn = "+ "'" + agentNamn +"'");
        infoRubrik.setText("Ny ändring har gjorts");
             
         }
         
         if(kategori.equals("Namn")){
        idb.update("UPDATE Agent SET Namn = "+ "'"+ nyInfo + "'" + " where namn = "+ "'" + agentNamn +"'");
        infoRubrik.setText("Ny ändring har gjorts");
         }
         
         if(kategori.equals("Telefon")){
        idb.update("UPDATE Agent SET Telefon = "+ "'"+ nyInfo + "'" + " where namn = "+ "'" + agentNamn +"'");
        infoRubrik.setText("Ny ändring har gjorts");
        }
         
         if(kategori.equals("Omrade")){
        String fragaOmrade = "Select Omrades_ID from Omrade where Benamning =" + "'" +nyInfo+"'";
        String resultatInt = idb.fetchSingle(fragaOmrade);
        int omradesInt = Integer.parseInt(resultatInt);
        idb.update("UPDATE Agent SET Omrade = "+ omradesInt + " where namn = "+ "'" + agentNamn +"'");
        infoRubrik.setText("Ny ändring har gjorts");
        }
        
        if(kategori.equals("Status")){
            String hamtaStatus = boxMedStatus.getSelectedItem().toString();
            idb.update("UPDATE Agent set Administrator =" + "'"+ hamtaStatus + "'" + " where namn = " +"'"+ agentNamn + "'" );
        }
         
         
       }catch (InfException e){
           
           
           
           
           
       }
    }//GEN-LAST:event_andraKnappActionPerformed

    private void valjAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjAgentActionPerformed
        infoRubrik.setVisible(true);
        kategoriBox.setVisible(true);
        valjOmradeKnapp.setVisible(true);
        ValjStatusKnapp.setVisible(true);
        nyInfoTextRuta.setVisible(true);
        rubrik2.setVisible(true);
        
    }//GEN-LAST:event_valjAgentActionPerformed

    private void valjOmradeKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjOmradeKnappActionPerformed
    boxMedOmraden.setVisible(true);
    fyllBoxMedAgentNamn();
   
    }//GEN-LAST:event_valjOmradeKnappActionPerformed

    private void ValjStatusKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValjStatusKnappActionPerformed
       boxMedStatus.setVisible(true);
    }//GEN-LAST:event_ValjStatusKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraInformationOmAgenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraInformationOmAgenter(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ValjStatusKnapp;
    private javax.swing.JButton andraKnapp;
    private javax.swing.JComboBox<String> boxMedAgenter;
    private javax.swing.JComboBox<String> boxMedOmraden;
    private javax.swing.JComboBox<String> boxMedStatus;
    private javax.swing.JLabel infoRubrik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> kategoriBox;
    private javax.swing.JTextField nyInfoTextRuta;
    private javax.swing.JLabel rubrik2;
    private javax.swing.JButton valjAgent;
    private javax.swing.JButton valjOmradeKnapp;
    // End of variables declaration//GEN-END:variables
}
