/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;


/**
 *
 * @author filippabostrom
 */
public class inloggningsSida extends javax.swing.JFrame {
    private static InfDB idb;
    private HashMap <String,String> agenter;

    /**
     * Creates new form inloggningsSida
     * @param idb
     */
    public inloggningsSida(InfDB idb) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;
        agenter = new HashMap <>();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startRubrik = new javax.swing.JLabel();
        anvandarnamnRubrik = new javax.swing.JLabel();
        anvandarnamnFalt = new javax.swing.JTextField();
        losenordRubrik = new javax.swing.JLabel();
        losenordFalt = new javax.swing.JPasswordField();
        loggaIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startRubrik.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        startRubrik.setText("Vänligen ange användarnamn och lösenord!");

        anvandarnamnRubrik.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        anvandarnamnRubrik.setText("Användarnamn:");

        anvandarnamnFalt.setColumns(7);

        losenordRubrik.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        losenordRubrik.setText("Lösenord:");

        losenordFalt.setColumns(7);

        loggaIn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        loggaIn.setText("Logga in");
        loggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggaInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(startRubrik))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(losenordRubrik)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(anvandarnamnFalt)
                                .addComponent(anvandarnamnRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(losenordFalt)
                                .addComponent(loggaIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(startRubrik)
                .addGap(36, 36, 36)
                .addComponent(anvandarnamnRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anvandarnamnFalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(losenordRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(losenordFalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(loggaIn)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggaInActionPerformed
       
        
        
          
  
        
        try{
            String anvandarNamn = anvandarnamnFalt.getText();
            String losen = losenordFalt.getText();
            String fraga = "SELECT Losenord from Agent where Namn =" + "'" + anvandarNamn + "'";
            String resultat = idb.fetchSingle(fraga);
            
          if(losen.equals(resultat)){
              loggaIn.setText("du loggas in");
              new AgentMeny(idb).setVisible(true);
           
          
          
            }else {
               startRubrik.setText("Du angav fel användarnamn eller lösenord ");
          }
          }catch(InfException e) {
                  
                  }
    
 
        
        
        

    }//GEN-LAST:event_loggaInActionPerformed
         
        
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anvandarnamnFalt;
    private javax.swing.JLabel anvandarnamnRubrik;
    private javax.swing.JButton loggaIn;
    private javax.swing.JPasswordField losenordFalt;
    private javax.swing.JLabel losenordRubrik;
    private javax.swing.JLabel startRubrik;
    // End of variables declaration//GEN-END:variables
        
}

