/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;


/**
 *
 * @author filippabostrom
 */
public class inloggningsSida extends javax.swing.JFrame {
    private static InfDB idb;
    private HashMap <String,String> agenter;

    /**
     * Creates new form inloggningsSida
     * @param idb
     */
    public inloggningsSida(InfDB idb) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;
        agenter = new HashMap <>();
    }
    
    
    private void fyllBoxMedAlienNamn() { //en metod som fyller komboboxen med alla alien som finns i alientabellen 
        String fraga = "SELECT namn from Alien"; //hämtar alla aliens från databasen som finns i alientabellen 
        
        ArrayList <String> allaAlienNamn; //skapar en arraylist av alienobjekt av typen string 
        
        try {
            allaAlienNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAlienNamn) {
                boxMedAnvandarnamn.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    private void fyllBoxAgentNamn() { //en metod som fyller komboboxen med alla agenter som finns i agenttabellen 
        String fraga = "SELECT namn from Agent"; //hämtar alla agenter från databasen som finns i agenttabellen 
        
        ArrayList <String> allaAgentNamn; //skapar en arraylist av agentobjekt av typen string 
        
        try {
            allaAgentNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAgentNamn) {
                boxMedAnvandarnamn.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
     private void fyllBoxAgentAdminNamn() { //en metod som fyller komboboxen med alla agenter som finns i agenttabellen som är administratörer
        String fraga = "SELECT namn from Agent where administrator = 'J' "; //hämtar alla agenter från databasen som finns i agenttabellen som är administratörer
        
        ArrayList <String> allaAgentAdminNamn; //skapar en arraylist av agentobjekt av typen string 
        
        try {
            allaAgentAdminNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAgentAdminNamn) {
                boxMedAnvandarnamn.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startRubrik = new javax.swing.JLabel();
        anvandarnamnRubrik = new javax.swing.JLabel();
        losenordRubrik = new javax.swing.JLabel();
        losenordFalt = new javax.swing.JPasswordField();
        loggaIn = new javax.swing.JButton();
        titelAlternativ = new javax.swing.JComboBox<>();
        boxMedAnvandarnamn = new javax.swing.JComboBox<>();
        valjInloggningssatt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startRubrik.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startRubrik.setText("Vänligen ange titel och logga in");

        anvandarnamnRubrik.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        anvandarnamnRubrik.setText("Användarnamn:");

        losenordRubrik.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        losenordRubrik.setText("Lösenord:");

        losenordFalt.setColumns(7);

        loggaIn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        loggaIn.setText("Logga in");
        loggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggaInActionPerformed(evt);
            }
        });

        titelAlternativ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agent", "Administratör", "Alien" }));
        titelAlternativ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titelAlternativActionPerformed(evt);
            }
        });

        valjInloggningssatt.setText("Välj");
        valjInloggningssatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjInloggningssattActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(boxMedAnvandarnamn, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(losenordRubrik, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(anvandarnamnRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(titelAlternativ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valjInloggningssatt)
                            .addGap(29, 29, 29))
                        .addComponent(loggaIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(losenordFalt, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(startRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titelAlternativ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valjInloggningssatt))
                .addGap(18, 18, 18)
                .addComponent(anvandarnamnRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxMedAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(losenordRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(losenordFalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loggaIn)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggaInActionPerformed
       
        
        // validering som ser till att textfälten inte är tomma, samt ger ifrån sig ett felmeddelande
          
          if(Validering.textFaltHarVarde(losenordFalt)){
              
          }
          
          //  här sker ett val i en komboBox, där man väljer om man vill logga in som Agent, Alien eller Administratör
          if(titelAlternativ.getSelectedItem().equals("Agent")) {
              
          
          
        try{
            String anvandarNamnAgent = boxMedAnvandarnamn.getSelectedItem().toString(); // hämtar det angivna användarnamnen
            String losenAgent = losenordFalt.getText(); // hämtar det angivna lösenordet
            String fragaAgent = "SELECT Losenord from Agent where Namn =" + "'" + anvandarNamnAgent + "'"; // fråga till databasen som hämtar det lösenord som stämmer överns med det angivna användarnamnet
            String resultat = idb.fetchSingle(fragaAgent); // i varibeln resultat hålls svaret på frågan
            
          if(losenAgent.equals(resultat)){ // sker en if-sats som kollar om lösenordet som angivits i lösenordsrutan stämmer överns med resultaten från frågan till databasen
              loggaIn.setText("du loggas in"); // om det stämmer överens så loggas man in
              new AgentMeny(idb).setVisible(true); // och en agent i detta fall blir flyttad till JFramen (agentMeny)
           
          
          
            }else { // skriver man fel lösenord får man ett felmeddelande i rubriken
               startRubrik.setText("Du angav fel användarnamn eller lösenord ");
          }
          }catch(InfException e) {
                  
                  }
          }
          
        // här sker ett val i komboBoxen där man väljer att logga in som Administratör
        if(titelAlternativ.getSelectedItem().equals("Administratör")){
          
            
            
           try{
            // här väljs den agent som man vill logga in som 
            String anvandarNamn = boxMedAnvandarnamn.getSelectedItem().toString();
            String losen = losenordFalt.getText(); // här hämtas det lösenord som användaren skrivit in i lösenordsRutan 
            String fraga = "SELECT Losenord from Agent where administrator = 'J' and Namn =" + "'" + anvandarNamn + "'"; // här hämtas lösenordet hos den valda agents namn ut, här kollas det också att agenten är administratör
            
          
            String resultat = idb.fetchSingle(fraga);
            
          if(losen.equals(resultat)){ // om lösenordet som angetts stämmer överens med lösenordet i databasen sker en inloggning
              loggaIn.setText("du loggas in");
              new AdministratorMeny(idb).setVisible(true); // flyttas över till administratörmenyn
           
          
          
            }else {  // stämmer det inte får användaren ett meddelande i rubriken 
               startRubrik.setText("Du angav fel användarnamn eller lösenord");
          }
          }catch(InfException e) {
                  
              
          }
        }
            // här sker ett val i komboBoxen där man väljer att logga in som alien
            if(titelAlternativ.getSelectedItem().equals("Alien")) {
                
            
           
            try{
            // här väljs den alien som man vill logga in som 
            String anvandarNamnAlien = boxMedAnvandarnamn.getSelectedItem().toString(); // hämtar ut det valda namnet från komboBoxen
            String losenAlien = losenordFalt.getText(); // hämtar ut det angivna lösenordet 
            String fragaAlien = "SELECT Losenord from Alien where Namn =" + "'" + anvandarNamnAlien + "'"; // här hämtas lösenordet från databasen för den valda alienen ut 
            String resultat = idb.fetchSingle(fragaAlien);
                 
            if(losenAlien.equals(resultat)){ //  om lösenordet som angetts stämmer överens med lösenordet i databasen sker en inloggning
              loggaIn.setText("du loggas in");
              
              new AlienMeny(idb).setVisible(true); // flyttas över till alienMenyn
          
          }else{ // stämmer inte lösenordet överens får användaren ett meddelande i rubriken 
             startRubrik.setText("Du angav fel användarnamn eller lösenord ");
          }
          
          }catch(InfException e) {
              JOptionPane.showMessageDialog(null, "Något gick fel");
                 System.out.println("internt felmeddelande" + e.getMessage());
          }
          
                
    
            
           }
        
       
       
        

    }//GEN-LAST:event_loggaInActionPerformed

    private void titelAlternativActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titelAlternativActionPerformed
      
        
        
    }//GEN-LAST:event_titelAlternativActionPerformed

    private void valjInloggningssattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjInloggningssattActionPerformed
      
        // tre if-satser som kollar vad man vill logga in som, som fyller komboBoxen med namn av det valde alternativet
        // Väljs "Administratör" fylls alltså komboBoxen med alla administratörer som finns i databasen
        
        if(titelAlternativ.getSelectedItem().equals("Agent")){
            fyllBoxAgentNamn(); 
        }
      
      if(titelAlternativ.getSelectedItem().equals("Alien")){
            fyllBoxMedAlienNamn(); 
        }
      
      if(titelAlternativ.getSelectedItem().equals("Administratör")){
            fyllBoxAgentAdminNamn(); 
        }
        
        
    }//GEN-LAST:event_valjInloggningssattActionPerformed
         
        
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anvandarnamnRubrik;
    private javax.swing.JComboBox<String> boxMedAnvandarnamn;
    private javax.swing.JButton loggaIn;
    private javax.swing.JPasswordField losenordFalt;
    private javax.swing.JLabel losenordRubrik;
    private javax.swing.JLabel startRubrik;
    private javax.swing.JComboBox<String> titelAlternativ;
    private javax.swing.JButton valjInloggningssatt;
    // End of variables declaration//GEN-END:variables

   
        
}

