/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author filippabostrom
 */
public class KollaRegistreradeAlienDatum extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form kollaRegistreradeAlienDatum
     */
    public KollaRegistreradeAlienDatum(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllBox1MedDatum();
        fyllBox2MedDatum();
    }
    
    
    private void fyllBox1MedDatum () {
        
        String fraga = "SELECT Registreringsdatum from Alien";
        ArrayList<String> datum1Lista;
       
          
          try{
         
           
           datum1Lista = idb.fetchColumn(fraga);
           
           for(String datum: datum1Lista){
            boxDatum1.addItem(datum);
           }
           
          }catch(InfException e){
              JOptionPane.showMessageDialog(null, "Något gick fel");
          }
        
        
        
        
        
        
    }
    
    
     private void fyllBox2MedDatum () {
        
        String fraga = "SELECT Registreringsdatum from Alien";
        ArrayList<String> datum2Lista;
       
          
          try{
         
           
           datum2Lista = idb.fetchColumn(fraga);
           
           for(String datum: datum2Lista){
            boxDatum2.addItem(datum);
           }
           
          }catch(InfException e){
              JOptionPane.showMessageDialog(null, "Något gick fel");
          }
        
        
        
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rubrikDatum = new javax.swing.JLabel();
        boxDatum1 = new javax.swing.JComboBox<>();
        boxDatum2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visaAlien = new javax.swing.JTextArea();
        välKnapp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rubrikDatum.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rubrikDatum.setText("Välj datum");

        jLabel2.setText("Från:");

        jLabel3.setText("Till:");

        visaAlien.setColumns(20);
        visaAlien.setRows(5);
        jScrollPane1.setViewportView(visaAlien);

        välKnapp.setText("Välj");
        välKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                välKnappActionPerformed(evt);
            }
        });

        jLabel1.setText("Inloggad som agent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rubrikDatum)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boxDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(välKnapp))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rubrikDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(välKnapp))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void välKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_välKnappActionPerformed
        
        visaAlien.setText("");
        
        ArrayList<HashMap<String,String>> infoOmAlien;
        try{
        String datum1 = boxDatum1.getSelectedItem().toString();
        String datum2 = boxDatum2.getSelectedItem().toString();
        String fraga = "Select Alien_ID, Namn, Registreringsdatum from Alien where Registreringsdatum > '" + datum1 +"' and registreringsdatum < '" + datum2 + "';";
        infoOmAlien = idb.fetchRows(fraga);
        
        
        for(HashMap<String,String> datum :infoOmAlien){
           visaAlien.append(datum.get("Alien_ID")+ "\t");
           visaAlien.append(" " + datum.get("Namn")+ "\t");
           visaAlien.append(" " + datum.get("Registreringsdatum")+ "\n");
            
            
        }
        
        }catch(InfException e){
            
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("internt felmeddelande" + e.getMessage());
        }
        
    }//GEN-LAST:event_välKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KollaRegistreradeAlienDatum(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDatum1;
    private javax.swing.JComboBox<String> boxDatum2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rubrikDatum;
    private javax.swing.JTextArea visaAlien;
    private javax.swing.JButton välKnapp;
    // End of variables declaration//GEN-END:variables
}
