/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author filippabostrom
 */
public class kollaRegistreradeAlienDatum extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form kollaRegistreradeAlienDatum
     */
    public kollaRegistreradeAlienDatum(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllBox1MedDatum(); 
        fyllBox2MedDatum();
    }
    
    
    private void fyllBox1MedDatum () {
        
        // metod som fyller en komboBox med registreringsdatum 
        
        String fraga = "SELECT Registreringsdatum from Alien"; // hämtar ut registreringsdatum från databasen
        
        ArrayList<String> datum1Lista; // ArrayList som håller i värdena som hämtats ut 
       
          
          try{
         
           
           datum1Lista = idb.fetchColumn(fraga);
           
           for(String datum: datum1Lista){ // for-each-loop som lägger till alla datum i komboboxen
            boxDatum1.addItem(datum);
           }
           
          }catch(InfException e){
              JOptionPane.showMessageDialog(null, "Något gick fel");
          }
        
        
        
        
        
        
    }
    
     // metod som fyller den andra komboBoxen med registreringsdatum
     private void fyllBox2MedDatum () {
        
        String fraga = "SELECT Registreringsdatum from Alien";
        ArrayList<String> datum2Lista;
       
          
          try{
         
           
           datum2Lista = idb.fetchColumn(fraga);
           
           for(String datum: datum2Lista){
            boxDatum2.addItem(datum);
           }
           
          }catch(InfException e){
              JOptionPane.showMessageDialog(null, "Något gick fel");
          }
        
        
        
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rubrikDatum = new javax.swing.JLabel();
        boxDatum1 = new javax.swing.JComboBox<>();
        boxDatum2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visaAlien = new javax.swing.JTextArea();
        välKnapp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rubrikDatum.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rubrikDatum.setText("Välj datum");

        jLabel2.setText("Från:");

        jLabel3.setText("Till:");

        visaAlien.setColumns(20);
        visaAlien.setRows(5);
        jScrollPane1.setViewportView(visaAlien);

        välKnapp.setText("Välj");
        välKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                välKnappActionPerformed(evt);
            }
        });

        jLabel1.setText("Inloggad som agent");

        jLabel4.setText("Alien_ID");

        jLabel5.setText("Namn");

        jLabel6.setText("Registreringsdatum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rubrikDatum)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(boxDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(välKnapp))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rubrikDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(välKnapp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void välKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_välKnappActionPerformed
        
        
        
        visaAlien.setText("");
        
        // skapas en ArrayList av hashMap som håller information om Alien
        
        ArrayList<HashMap<String,String>> infoOmAlien;
        try{
        String datum1 = boxDatum1.getSelectedItem().toString(); // hämtar ut den valda datumet från komboBoxen
        String datum2 = boxDatum2.getSelectedItem().toString(); // hämtar ut det andra datumet från den andra komboBoxen 
        
        // hämtar ut information om aliens som är registrerade mellan två olika datum
        // kollar om registreringsdatumet i databasen är större än datum1( första valda registreringsdatumet) och mindre än datum2(andra valda registrerigsdatumet)
        String fraga = "Select Alien_ID, Namn, Registreringsdatum from Alien where Registreringsdatum > '" + datum1 +"' and registreringsdatum < '" + datum2 + "';";
        infoOmAlien = idb.fetchRows(fraga);
        
        // for-each-loop som skriver ut information om de aliens som är registrerade inom spannet datum1 till datum2
        for(HashMap<String,String> datum :infoOmAlien){
           visaAlien.append(datum.get("Alien_ID")+ "\t");
           visaAlien.append(" " + datum.get("Namn")+ "\t");
           visaAlien.append(" " + datum.get("Registreringsdatum")+ "\n");
            
            
        }
        
        }catch(InfException e){
            
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("internt felmeddelande" + e.getMessage());
        }
        
    }//GEN-LAST:event_välKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kollaRegistreradeAlienDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kollaRegistreradeAlienDatum(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDatum1;
    private javax.swing.JComboBox<String> boxDatum2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rubrikDatum;
    private javax.swing.JTextArea visaAlien;
    private javax.swing.JButton välKnapp;
    // End of variables declaration//GEN-END:variables
}
