/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


/**
 *
 * @author filip
 */
public class VisaAllInformationAlien extends javax.swing.JFrame {
private static InfDB idb;

    /**
     * Creates new form VisaAllInformationAlien
     */
    public VisaAllInformationAlien(InfDB idb) {
        initComponents();
        this.idb=idb;
        fyllBoxMedNamn();
    }

    
    private void fyllBoxMedNamn() {
        String fraga = "SELECT namn from Alien";
        
        ArrayList <String> allaAlienNamn;
        
        try {
            allaAlienNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAlienNamn) {
                valjNamn.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textRutaAllInfo = new javax.swing.JTextArea();
        skrivInAliennamnRubrik = new javax.swing.JLabel();
        informationOmAlienRubrik = new javax.swing.JLabel();
        väljKnapp = new javax.swing.JButton();
        valjNamn = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textRutaAllInfo.setColumns(20);
        textRutaAllInfo.setRows(5);
        jScrollPane1.setViewportView(textRutaAllInfo);

        skrivInAliennamnRubrik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        skrivInAliennamnRubrik.setText("Skriv in Aliennamn ");

        informationOmAlienRubrik.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        informationOmAlienRubrik.setText("Information om Alien");
        informationOmAlienRubrik.setToolTipText("");

        väljKnapp.setText("Välj ");
        väljKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                väljKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationOmAlienRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(skrivInAliennamnRubrik)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(valjNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(väljKnapp)))
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(informationOmAlienRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(skrivInAliennamnRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(väljKnapp)
                    .addComponent(valjNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void väljKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_väljKnappActionPerformed
        
        
       textRutaAllInfo.setText("");
       ArrayList<HashMap<String, String>> allInfoAlien;
       
        try{
            String valtAlienNamn = valjNamn.getSelectedItem().toString();
            String fraga = "SELECT * from Alien where namn = "+ "'" + valtAlienNamn + "'";
            allInfoAlien = idb.fetchRows(fraga);
            
            for(HashMap<String, String> alien: allInfoAlien){
            textRutaAllInfo.append(alien.get("Alien_ID")+ "\t");
            textRutaAllInfo.append(" " + alien.get("Registreringsdatum")+ "\t");
            textRutaAllInfo.append(" " + alien.get("Losenord") + "\t");
            textRutaAllInfo.append(" " + alien.get("Namn") + "\t");
            textRutaAllInfo.append(" " + alien.get("Telefon")+ "\t");
            textRutaAllInfo.append(" " + alien.get("Plats")+ "\t");
            textRutaAllInfo.append(" " + alien.get("Ansvarig_Agent")+"\n");
            }
                
        
        
        }catch(InfException e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel");
                    System.out.println("Internt felmeddelande" + e.getMessage());
        }
          catch(Exception ettUndantag){
                  JOptionPane.showMessageDialog(null, "ett fel uppstod");
                  System.out.println("Internt felmeddlenade" + ettUndantag.getMessage());
                  }
        
        
    
    }//GEN-LAST:event_väljKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaAllInformationAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaAllInformationAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaAllInformationAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaAllInformationAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaAllInformationAlien(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel informationOmAlienRubrik;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel skrivInAliennamnRubrik;
    private javax.swing.JTextArea textRutaAllInfo;
    private javax.swing.JComboBox<String> valjNamn;
    private javax.swing.JButton väljKnapp;
    // End of variables declaration//GEN-END:variables
}
