/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;
import static java.lang.Integer.parseInt;
import oru.inf.InfDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author filip
 */
public class ÄndraAgentSomÄrOmrådeschef extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form ÄndraAgentSomÄrOmrådeschef
     */
    public ÄndraAgentSomÄrOmrådeschef(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllBoxMedAgentNamn();
        fyllBoxMedOmrade();
    }

     private void fyllBoxMedAgentNamn() {
        
         
        String fraga = "SELECT namn from Agent";
        
        ArrayList <String> allaAgentNamn;
        
        try {
            allaAgentNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAgentNamn) {
                namnPåAgenter.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }

     private void fyllBoxMedOmrade() {
         String fraga = "SELECT benamning from omrade";
         
         ArrayList<String> allaOmradeNamn;
         
          try {
            allaOmradeNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaOmradeNamn) {
                namnPaOmradeBox.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
         
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rubrik = new javax.swing.JLabel();
        namnPåAgenter = new javax.swing.JComboBox<>();
        väljAgentRubrik = new javax.swing.JLabel();
        valjOmrådeRubrik = new javax.swing.JLabel();
        ändraOmrådeschefKnapp = new javax.swing.JButton();
        namnPaOmradeBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rubrik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rubrik.setText("Ändra områdeschef ");

        väljAgentRubrik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        väljAgentRubrik.setText("Välj agent:");

        valjOmrådeRubrik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valjOmrådeRubrik.setText("Välj område:");

        ändraOmrådeschefKnapp.setText("Ändra Områdeschef");
        ändraOmrådeschefKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ändraOmrådeschefKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(väljAgentRubrik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namnPåAgenter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valjOmrådeRubrik)
                            .addComponent(namnPaOmradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(ändraOmrådeschefKnapp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(rubrik)))
                .addGap(129, 151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(rubrik)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(väljAgentRubrik)
                    .addComponent(valjOmrådeRubrik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namnPåAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namnPaOmradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(ändraOmrådeschefKnapp)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ändraOmrådeschefKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ändraOmrådeschefKnappActionPerformed
        try{
          String agentNamn = namnPåAgenter.getSelectedItem().toString();
          String fraga = "SELECT agent_ID from agent where Namn ='" + agentNamn + "'";
          String resultat = idb.fetchSingle(fraga);
          int agentInt = Integer.parseInt(resultat);
          int rattAgentId = agentInt;
          
          String omrade = namnPaOmradeBox.getSelectedItem().toString();
          System.out.println(omrade);
          String fraga1 = "SELECT Omrades_ID from omrade where benamning = " + "'" + omrade + "'";
          String resultatFraga1 = idb.fetchSingle(fraga1);
          String fragaOmrade = "SELECT Agent_ID from omradeschef where Omrade = " + "'" + resultatFraga1 + "'";
          String resultatOmrade = idb.fetchSingle(fragaOmrade);
          System.out.println(resultatOmrade);
          int agentNyttID = Integer.parseInt(resultatOmrade);
          int omradet = Integer.parseInt(resultatOmrade);
          System.out.println(omradet);
        
          idb.update("UPDATE omradeschef SET agent_ID = " + "'" + rattAgentId+ "'" + "where agent_ID = " + "'" + agentNyttID + "'");
          
          
       
         rubrik.setText("Områdeschef uppdaterad");
          
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Agenten är redan områdeschef");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }   
         
        
    }//GEN-LAST:event_ändraOmrådeschefKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÄndraAgentSomÄrOmrådeschef(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> namnPaOmradeBox;
    private javax.swing.JComboBox<String> namnPåAgenter;
    private javax.swing.JLabel rubrik;
    private javax.swing.JLabel valjOmrådeRubrik;
    private javax.swing.JLabel väljAgentRubrik;
    private javax.swing.JButton ändraOmrådeschefKnapp;
    // End of variables declaration//GEN-END:variables
}
