/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfException;
import oru.inf.InfDB;
import static java.lang.Integer.parseInt;



/**
 *
 * @author filip
 */
public class ÄndraAgentSomÄrKontorschef extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form ÄndraAgentSomÄrKontorschef
     */
    public ÄndraAgentSomÄrKontorschef(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllBoxMedAgentNamn();
        fyllBoxMedKontorsbetecknig();
        
        
    }

    private void fyllBoxMedAgentNamn() {
        
         
        String fraga = "SELECT namn from Agent";
        
        ArrayList <String> allaAgentNamn;
        
        try {
            allaAgentNamn = idb.fetchColumn(fraga);
            
            for(String namn:allaAgentNamn) {
                valjAgentBox.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    private void fyllBoxMedKontorsbetecknig() {
        
         
        String fraga = "SELECT kontorsBeteckning from kontorschef";
        
        ArrayList <String> allaKontorsbeteckning;
        
        try {
            allaKontorsbeteckning = idb.fetchColumn(fraga);
            
            for(String namn:allaKontorsbeteckning) {
                valjKontorsBeteckningBox.addItem(namn);   
            }
            
        }catch(InfException e) {
            JOptionPane.showMessageDialog(null, "fel");
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rubrik = new javax.swing.JLabel();
        valjAgentBox = new javax.swing.JComboBox<>();
        valjAgentRubrik = new javax.swing.JLabel();
        valjKontorsbeteckningRubrik = new javax.swing.JLabel();
        andraKontorschefKnapp = new javax.swing.JButton();
        valjKontorsBeteckningBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rubrik.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rubrik.setText("Ändra kontorschef ");

        valjAgentRubrik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valjAgentRubrik.setText("Välj agent:");

        valjKontorsbeteckningRubrik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valjKontorsbeteckningRubrik.setText("Välj kontorsbeteckning:");

        andraKontorschefKnapp.setText("Ändra kontorschef");
        andraKontorschefKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraKontorschefKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rubrik)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valjAgentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valjAgentRubrik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valjKontorsbeteckningRubrik)
                            .addComponent(valjKontorsBeteckningBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(andraKontorschefKnapp)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rubrik)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(valjKontorsbeteckningRubrik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valjKontorsBeteckningBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(valjAgentRubrik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valjAgentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(andraKontorschefKnapp)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    private void andraKontorschefKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraKontorschefKnappActionPerformed
     try {
         String agentNamn = valjAgentBox.getSelectedItem().toString();
         String fraga = "SELECT Agent_ID from agent where namn = " + "'" + agentNamn + "'";
         String resultat = idb.fetchSingle(fraga);
         int agentInt = Integer.parseInt(resultat);
         int rattAgentID = agentInt;
         
         String kontorsbenämning = valjKontorsBeteckningBox.getSelectedItem().toString();
         System.out.println(kontorsbenämning);
         String fraga2 = "Select Agent_id from kontorschef where Kontorsbeteckning = " + "'" + kontorsbenämning + "'";
         String resultat2 = idb.fetchSingle(fraga2);
         int agentNyttID = Integer.parseInt(resultat2);
         idb.update("UPDATE kontorschef SET Agent_ID = " + "'" + rattAgentID + "'" +"where agent_id = " + "'" +agentNyttID+"'");
         rubrik.setText("kontorschef uppdaterad");
         
     } catch(InfException e) {
         JOptionPane.showMessageDialog(null, "Gick inte att uppdatera kontorschef");
         System.out.println("Internt felmeddelande" + e.getMessage());
          
     }  
        
    }//GEN-LAST:event_andraKontorschefKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrKontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrKontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrKontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraAgentSomÄrKontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÄndraAgentSomÄrKontorschef(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton andraKontorschefKnapp;
    private javax.swing.JLabel rubrik;
    private javax.swing.JComboBox<String> valjAgentBox;
    private javax.swing.JLabel valjAgentRubrik;
    private javax.swing.JComboBox<String> valjKontorsBeteckningBox;
    private javax.swing.JLabel valjKontorsbeteckningRubrik;
    // End of variables declaration//GEN-END:variables
}
